### ISSUE TITLE
"RuntimeError: uvloop does not support Windows at the moment"

### ISSUE THREAD

**Issue by Eshan276** [test-zeus-ai/testzeus-hercules#6]
**Describe the bug**
When trying install it , getting "RuntimeError: uvloop does not support Windows at the moment"
is it only supported at linux at this moment ?

**To Reproduce**
1. Go to terminal
2. run pip install testzeus-hercules

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11

**Comment by shriyanshagnihotri** [comment]
@Eshan276 thanks for raising the bug. This is a bug.

for the time being till we figure out a way to solve this in Windows native.

there are few things I can suggest as workaround.
0) Run this with docker.
1) Run this in a VirtualBox with any linux flavor.
2) Run this in Windows WSL, in that case you can even connect it with VScode, also for running the browser in interactive mode, you have to take a path of CDP in such case. (https://chromedevtools.github.io/devtools-protocol/)
check this section: https://github.com/test-zeus-ai/testzeus-hercules?tab=readme-ov-file#understanding-the-environment-file-env

We also request if you have a solution to this problem, we welcome the PR. Else will put this in the triage list of our release plan.

Thanks.

**Comment by shriyanshagnihotri** [comment]
Awesome thanks @hiteshodedara12, we can release a patch on this, after our test suite passes with the removal of uvloop.

I am removing more packages in the next release, to make this lightweight, the poetry file is too heavy.

**Comment by shriyanshagnihotri** [comment]
@hiteshodedara12 @Eshan276 : Please try https://github.com/test-zeus-ai/testzeus-hercules/releases/tag/0.0.10
we tried to clean the packages and remove some code that was causing failure.
